name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .        # makes scala_runner available
          pip install pytest httpx

      - name: Run Python tests
        run: pytest -q

  scala:
    runs-on: ubuntu-latest

    # tell GH Actions to use this Docker image as the job's runtime
    container:
      image: virtuslab/scala-cli:latest
      # pull-policy: if-not-present  # uncomment if you want to cache locally

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Scala CLI tests
        # now scala-cli is on PATH
        run: scala-cli test