name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .        # makes scala_runner available

      - name: Verify Docker is available
        run: |
          docker --version
          docker info

      - name: Pull SBT Docker image
        run: |
          docker pull sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.7_6_1.11.2_3.7.1

      - name: Run unit tests
        run: pytest -v -m "not integration"

      - name: Run integration tests
        # these actually invoke Docker, so give more time
        run: pytest -v -m integration --tb=short