name: Build, Publish & Test Docker Image

on:
  push:
    # match ANY tag (you can tighten this to e.g. 'v*' if you only want semantic-version tags)
    tags:
      - '*'  

# 2) Give GITHUB_TOKEN permissions to publish to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:19.03-dind
        privileged: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    outputs:
      # export the full image name (including the tag) for downstream jobs
      image: ${{ steps.set-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Tag the image with both the raw tag and 'latest'
          tags: |
            ghcr.io/${{ github.repository_owner }}/scala-runner:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/scala-runner:latest

      - name: Set image output
        id: set-image
        run: |
          # Here we choose to downstream-test the 'latest', but you could
          # easily switch to "${{ github.ref_name }}" if you prefer.
          echo "image=ghcr.io/${{ github.repository_owner }}/scala-runner:latest" \
            >> $GITHUB_OUTPUT

  integration-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:19.03-dind
        privileged: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository_owner }}/scala-runner:latest

      - name: Start container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/scala-runner:latest
          docker run -d --name scala-test \
            -p 8080:80 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            $IMAGE

      - name: Wait for API
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/ping | grep pong; then
              echo "API is up"
              exit 0
            fi
            sleep 2
          done
          echo "API did not start in time" >&2
          exit 1

      - name: Test Docker-in-Docker
        run: |
          PAYLOAD='{"code": "println(scala.util.Properties.versionString)","scala_version": "2.13"}'
          curl -s -X POST http://localhost:8080/run \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" | jq .

      - name: Cleanup
        run: docker rm -f scala-test