name: Build, Publish & Test Docker Image
on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:19.03-dind
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true       # ensures buildx is available
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          # reuse the same tags you had
          tags: |
            ghcr.io/${{ github.repository_owner }}/scala-runner:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/scala-runner:latest

      - name: Set image output
        id: set-image
        run: |
          # Here we choose to downstream-test the 'latest', but you could
          # easily switch to "${{ github.ref_name }}" if you prefer.
          echo "image=ghcr.io/${{ github.repository_owner }}/scala-runner:latest" \
            >> $GITHUB_OUTPUT

  integration-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:19.03-dind
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository_owner }}/scala-runner:latest

      - name: Start container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/scala-runner:latest
          docker run -d --name scala-test \
            -p 8080:80 \
            -v /tmp/:/tmp/ \
            -v /var/run/docker.sock:/var/run/docker.sock \
            $IMAGE

      - name: Wait for API
        run: |
          for i in {1..100}; do
            if curl -s http://localhost:8080/ping | grep pong; then
              echo "API is up"
              exit 0
            fi
            sleep 2
          done
          echo "API did not start in time" >&2
          exit 1

      - name: Test Docker-in-Docker
        run: |
          PAYLOAD='{"code":"println(scala.util.Properties.versionString)","scala_version":"2.13","file_extension":"sc"}'
          curl -s -X POST http://localhost:8080/run \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" | jq .

      - name: Cleanup
        run: docker rm -f scala-test